config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/albums/bandcamp_details', to: 'albums#extract_bandcamp_details', as: 'extract_bandcamp_details'

  resources :artists, :payees, :payouts, :albums, :tracks

  resources :merch_orders, path: '/merch/orders'
  put '/merch/orders/:id/refund', to: 'merch_orders#refund', as: 'refund_merch_order'
  resources :merch_fulfillments, path: '/merch/orders/fulfillments'

  resources :iam8bit_sales, path: 'merch/iam8bit'
  resources :merch
  resources :rendered_services, path: 'services_rendered'

  get '/reports', to: 'reports#index'
  get '/reports/projects', to: 'reports#projects'
  get '/reports/generate', to: 'reports#combined_excel_report', as: 'reports_generate'
  get '/reports/profit_and_loss', to: 'reports#profit_and_loss'
  get '/reports/:id/download', to: 'reports#download', as: 'reports_download'
  get '/issues', to: 'reports#needs_attention'

  scope path: '/products/:product_type/:product_id/splits' do
    get '/edit', to: 'splits#edit', as: 'edit_splits'
    post '/', to: 'splits#update', as: 'splits'

    post '/append', to: 'splits#append', as: 'append_split'
  end

  get '/imports', to: 'imports#index', as: 'imports'
  post '/imports/distrokid', to: 'imports#import_distrokid_streams'
  post '/imports/bandcamp', to: 'imports#import_bandcamp_sales'

  match '/internal/jobs' => DelayedJobWeb, :anchor => false, :via => [:get, :post], as: 'delayed_jobs'

  get '/privacy', to: 'static_pages#privacy'
  root 'static_pages#home'
end

app/models/merch_fulfillment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: merch_fulfillments
#
#  id                       :integer          not null, primary key
#  notes                    :text
#  printify_order_number    :string
#  production_cost_cents    :integer          default(0), not null
#  production_cost_currency :string           default("USD"), not null
#  shipped_on               :date
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  fulfilled_by_id          :integer
#
# Indexes
#
#  index_merch_fulfillments_on_fulfilled_by_id  (fulfilled_by_id)
#
# Foreign Keys
#
#  fulfilled_by_id  (fulfilled_by_id => admins.id)
#

# This record is created when a merch item is shipped. It records
# the cost of the product, so we can deduct it before calculating
# royalty costs.
# Royalties are not attributed until a merch item is fulfilled.
# Production cost is the cost of the item. It does not including shipping,
# bandcamp fees, or transaction fees; only the cost of the product.
# fulfilled_by_id is a pointer to the Admin who marked the product as shipped.
class MerchFulfillment < ApplicationRecord
  include MonitizedSum

  has_many :bandcamp_sales, dependent: :restrict_with_exception
  has_one :internal_merch_order, required: false, dependent: :restrict_with_exception
  # fulfilled by will be nil for internal merch orders
  belongs_to :fulfilled_by, class_name: 'Admin', optional: true

  monetize :production_cost_cents

  validates :production_cost_currency, inclusion: { in: Money.default_currency.iso_code }

  strip_attributes
end

app/controllers/merch_fulfillments_controller.rb
# frozen_string_literal: true

class MerchFulfillmentsController < ApplicationController
  before_action :raise_unless_admin!

  def new
    @bandcamp_transaction_id = params[:order_id]
    @sales = BandcampSale.unfulfilled_merch.where(bandcamp_transaction_id: params[:order_id])
    @merch_fulfillment = MerchFulfillment.new(shipped_on: Time.zone.today)
    restore_changes!(@merch_fulfillment)
  end

  def edit
    @merch_fulfillment = MerchFulfillment.find(params[:id])
    @sales = @merch_fulfillment.bandcamp_sales
    restore_changes!(@merch_fulfillment)
  end

  def create
    @bandcamp_transaction_id = params[:bandcamp_transaction_id]
    @merch_fulfillment = MerchFulfillment.new(fulfillment_params)
    ActiveRecord::Base.transaction do
      @merch_fulfillment.save!
      @sales = BandcampSale.merch.where(bandcamp_transaction_id: @bandcamp_transaction_id)
      @sales.find_each do |sale|
        sale.update!(merch_fulfillment: @merch_fulfillment)
      end
    end
    flash[:success] = 'Merch order marked shipped'
    redirect_to merch_orders_path
  rescue StandardError => e
    log_error!(e)
    flash[:danger] = e.message
    record_changes!(@merch_fulfillment)
    redirect_to new_merch_fulfillment_path(order_id: @bandcamp_transaction_id)
  end

  def update
    @merch_fulfillment = MerchFulfillment.find(params[:id])
    @merch_fulfillment.assign_attributes(fulfillment_params)
    @merch_fulfillment.save!
    flash[:success] = 'Merch order details updated'
    redirect_to merch_orders_path
  rescue StandardError => e
    log_error!(e)
    flash[:danger] = e.message
    record_changes!(@merch_fulfillment)
    redirect_to edit_merch_fulfillment_path(@merch_fulfillment)
  end

  private

  def fulfillment_params
    params.require(:merch_fulfillment).permit(
      :shipped_on,
      :production_cost_cents, :production_cost_currency,
      :printify_order_number, :notes
    ).tap do |params|
      params[:fulfilled_by_id] = current_user.admin.id
    end
  end
end

app/views/merch_fulfillments/_form.html.slim
p
  = "Order "
  code = @bandcamp_transaction_id
  - if @sales.first
    = " for placed on #{localized_date(@sales.first.purchased_at)} to #{@sales.first.shipping_destination}."
  br
  a.button target="_blank" href="https://fourth-strike.bandcamp.com/merch_orders?payment_id=#{@bandcamp_transaction_id}" View on Bandcamp

= hidden_field_tag 'bandcamp_transaction_id', @bandcamp_transaction_id

.field
  label.label.is-required Printify Order number
  .control
    = text_field :merch_fulfillment, :printify_order_number, class: 'input', placeholder: '1932959.123'

.field
  label.label.is-required Shipped on
  .control
    = text_field :merch_fulfillment, :shipped_on, type: 'date', class: 'input'

.field
  label.label.is-required Production Costs
  .control
    div vue-component="MoneyField" props={name: "merch_fulfillment[production_cost]", cents: @merch_fulfillment.production_cost_cents, currency: @merch_fulfillment.production_cost_currency}.to_json
    p This should be the cost to produce and ship the item. Use the "Total costs" field from Printify (cost of production, shipping, and tax).

.field
  label.label Notes
  .control
    = text_area :merch_fulfillment, :notes, class: 'textarea'

app/views/merch_fulfillments/edit.html.slim
section.section
  h1.is-size-2 Edit Fulfillment


  .columns
    .column.is-full.is-one-third-desktop

      = form_for(@merch_fulfillment, url: merch_fulfillment_path(@merch_fulfillment)) do |f|

        = render 'form', f: f

        .field
          .control
            = f.submit "Update", class: "button is-link"

app/views/merch_fulfillments/new.html.slim
section.section
  h1.is-size-2 Mark Merch Order Shipped


  .columns
    .column.is-full.is-one-third-desktop

      = form_tag(merch_fulfillments_path, method: :post) do

        = render 'form'

        .field
          .control
            = submit_tag "Mark Shipped", class: "button is-link"