config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/albums/bandcamp_details', to: 'albums#extract_bandcamp_details', as: 'extract_bandcamp_details'

  resources :artists, :payees, :payouts, :albums, :tracks

  resources :merch_orders, path: '/merch/orders'
  put '/merch/orders/:id/refund', to: 'merch_orders#refund', as: 'refund_merch_order'
  resources :merch_fulfillments, path: '/merch/orders/fulfillments'

  resources :iam8bit_sales, path: 'merch/iam8bit'
  resources :merch
  resources :rendered_services, path: 'services_rendered'

  get '/reports', to: 'reports#index'
  get '/reports/projects', to: 'reports#projects'
  get '/reports/generate', to: 'reports#combined_excel_report', as: 'reports_generate'
  get '/reports/profit_and_loss', to: 'reports#profit_and_loss'
  get '/reports/:id/download', to: 'reports#download', as: 'reports_download'
  get '/issues', to: 'reports#needs_attention'

  scope path: '/products/:product_type/:product_id/splits' do
    get '/edit', to: 'splits#edit', as: 'edit_splits'
    post '/', to: 'splits#update', as: 'splits'

    post '/append', to: 'splits#append', as: 'append_split'
  end

  get '/imports', to: 'imports#index', as: 'imports'
  post '/imports/distrokid', to: 'imports#import_distrokid_streams'
  post '/imports/bandcamp', to: 'imports#import_bandcamp_sales'

  match '/internal/jobs' => DelayedJobWeb, :anchor => false, :via => [:get, :post], as: 'delayed_jobs'

  get '/privacy', to: 'static_pages#privacy'
  root 'static_pages#home'
end

app/controllers/merch_orders_controller.rb
# frozen_string_literal: true

class MerchOrdersController < ApplicationController
  before_action :raise_unless_admin!

  def index
    @sales = BandcampSale.where(product_type: 'Merch')
    @sales = @sales.order(purchased_at: :desc, bandcamp_transaction_id: :asc, created_at: :desc)
    @sales = @sales.unfulfilled_merch if params[:unfulfilled].to_b
    @sales = @sales.where(bandcamp_transaction_id: params[:bandcamp_transaction_id]) if params[:bandcamp_transaction_id]
    @sales = @sales.where(product_id: params[:merch_id]) if params[:merch_id]
    @sales = @sales.paginate(page: params[:page] || 1, per_page: 200)
  end

  def refund
    @sales = BandcampSale.merch.where(bandcamp_transaction_id: params[:id])
    ActiveRecord::Base.transaction do
      @sales.each { |sale| sale.update!(refunded: true) }
    end
    flash[:success] = 'Order marked as refunded'
    redirect_to merch_orders_path
  rescue StandardError => e
    log_error!(e)
    flash[:danger] = e.message
    redirect_to merch_orders_path
  end
end

app/views/merch_orders/index.html.slim
h1.is-size-2
  - if params['unfulfilled'].to_b
    span Unfulfilled Merch Orders
  - else
    span Merch Orders

- if params['unfulfilled'].to_b && @sales.empty?
  p No orders require shipping at this time.

section.section
  = render_pagination(@sales)

  table.table
    thead
      tr
        th Purchase Date
        th Transaction
        th Destination
        th Product
        th Subtotal
        th Status
        th Production + Shipping Costs
        th Printify Order
        th
    tbody
      - current_order_id = nil
      - @sales.each do |sale|
        tr
          - if current_order_id != sale.bandcamp_transaction_id
            - expected = @sales.where(bandcamp_transaction_id: sale.bandcamp_transaction_id).count
            td rowspan=expected = localized_date(sale.purchased_at)
            td rowspan=expected
              a target="_blank" href="https://fourth-strike.bandcamp.com/merch_orders?payment_id=#{sale.bandcamp_transaction_id}"
                = sale.bandcamp_transaction_id
            td rowspan=expected = sale.shipping_destination
          td
            span = sale.product.name
            br
            code = sale.sku
            - if sale.option
              span = "[ #{sale.option} ]"

          - if current_order_id != sale.bandcamp_transaction_id
            td rowspan=expected style=(sale.refunded? ? 'text-decoration: line-through;' : '') = sale.subtotal_amount.format
            - if sale.refunded?
              td rowspan=expected Refunded
            - elsif sale.merch_fulfillment
              td.is-success rowspan=expected
                = localized_date(sale.merch_fulfillment.shipped_on)
            - else
              td rowspan=expected class=(sale.overdue? ? 'is-danger' : 'is-warning') Pending

          - if current_order_id != sale.bandcamp_transaction_id
            td rowspan=expected
              - if sale.merch_fulfillment
                = sale.merch_fulfillment.production_cost.format
                - if sale.merch_fulfillment.notes.present?
                  br
                  pre style="max-width: 100px"
                    = sale.merch_fulfillment.notes
          - if current_order_id != sale.bandcamp_transaction_id
            td rowspan=expected
              - if sale.merch_fulfillment&.printify_order_number.present?
                a target="_blank" href="https://printify.com/app/store/1932959/orders/1?sort=-created_at&searchKey=#{sale.merch_fulfillment.printify_order_number}"
                  = sale.merch_fulfillment.printify_order_number
            td rowspan=expected
              - unless sale.refunded?
                = button_to "Mark Refunded", refund_merch_order_path(id: sale.bandcamp_transaction_id), method: :put, class: "button"
                br
              - if sale.merch_fulfillment
                a.button href=edit_merch_fulfillment_path(sale.merch_fulfillment) Edit
              - else
                a.button href=new_merch_fulfillment_path(order_id: sale.bandcamp_transaction_id) Mark Shipped
          - current_order_id = sale.bandcamp_transaction_id

  = render_pagination(@sales)