config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/albums/bandcamp_details', to: 'albums#extract_bandcamp_details', as: 'extract_bandcamp_details'

  resources :artists, :payees, :payouts, :albums, :tracks

  resources :merch_orders, path: '/merch/orders'
  put '/merch/orders/:id/refund', to: 'merch_orders#refund', as: 'refund_merch_order'
  resources :merch_fulfillments, path: '/merch/orders/fulfillments'

  resources :iam8bit_sales, path: 'merch/iam8bit'
  resources :merch
  resources :rendered_services, path: 'services_rendered'

  get '/reports', to: 'reports#index'
  get '/reports/projects', to: 'reports#projects'
  get '/reports/generate', to: 'reports#combined_excel_report', as: 'reports_generate'
  get '/reports/profit_and_loss', to: 'reports#profit_and_loss'
  get '/reports/:id/download', to: 'reports#download', as: 'reports_download'
  get '/issues', to: 'reports#needs_attention'

  scope path: '/products/:product_type/:product_id/splits' do
    get '/edit', to: 'splits#edit', as: 'edit_splits'
    post '/', to: 'splits#update', as: 'splits'

    post '/append', to: 'splits#append', as: 'append_split'
  end

  get '/imports', to: 'imports#index', as: 'imports'
  post '/imports/distrokid', to: 'imports#import_distrokid_streams'
  post '/imports/bandcamp', to: 'imports#import_bandcamp_sales'

  match '/internal/jobs' => DelayedJobWeb, :anchor => false, :via => [:get, :post], as: 'delayed_jobs'

  get '/privacy', to: 'static_pages#privacy'
  root 'static_pages#home'
end

app/controllers/imports_controller.rb
# frozen_string_literal: true

class ImportsController < ApplicationController
  before_action :raise_unless_admin!

  def index; end

  def import_bandcamp_sales
    load_report(LoadBandcampJob)
  end

  def import_distrokid_streams
    load_report(LoadDistrokidJob)
  end

  private

  def load_report(job_class)
    path = Rails.root.join('storage/exports', params[:report].original_filename)
    File.binwrite(path, params[:report].read)
    job_class.perform_later(path.to_s)
    flash[:success] = 'Loading report. The data will update over the next couple of minutes'
    redirect_to imports_path
  end
end

app/views/imports/_last_updated.html.slim
.tags.has-addons
  span.tag Last Updated
  span.tag class=(last_updated > 1.month.ago ? 'is-primary' : (last_updated > 3.months.ago ? 'is-warning' : 'is-danger'))
    = localized_date(last_updated)

app/views/imports/index.html.slim
section.section
  h1.is-size-2 Data Import


  h3.is-size-4 Bandcamp Sales (Digital & Physical)
  = render('last_updated', last_updated: BandcampSale.maximum(:created_at))

  p
    span.is-bold Directions:
    ol
      li
        span Log into
        = ' '
        a href="https://#{Rails.application.config.app_config[:bandcamp][:url]}" target="_blank" Bandcamp
      li In the top right, click on the menu and go to "Tools"
      li Select the "Raw data report" and the appropriate time range
      li 
        | Make sure it's loading the necessary fields ("All artists", "Payment details", "Item details").
        | "Buyer details" can be ignored for privacy purposes, it isn't utilized
      li Click "Export raw data report"
      li Upload below

  = form_tag(imports_bandcamp_path, multipart: true) do
    = hidden_field_tag(:type, :bandcamp)
    = render('file_field', field_name: "report", placeholder: 'xxxx-xxxx_bandcamp_raw_data_xxx.csv')
    = submit_tag "Upload", class: "button is-primary"


  h3.is-size-4 DistroKid Streams
  = render('last_updated', last_updated: DistrokidSale.maximum(:created_at))

  p
    span.is-bold Directions:
    ol
      li
        span Log into
        = ' '
        a href="https://distrokid.com/mymusic/" target="_blank" DistroKid
      li Go to "Bank" and select "See excruciating detail"
      li Make sure it's loading everything ("All dates", "All artists", "All releases", "All stores")
      li Click the Download icon in the top right
      li Unzip the file
      li Upload below

  = form_tag(imports_distrokid_path, multipart: true) do
    = hidden_field_tag(:type, :distrokid)
    = render('file_field', field_name: "report", placeholder: 'results.csv')
    = submit_tag "Upload", class: "button is-primary"

  / TODO: paypal

  h3.is-size-4 iam8bit Sales
  = render('last_updated', last_updated: Iam8bitSale.maximum(:created_at))

  p
    span.is-bold Directions:
    ol
      li
        span Check
        = ' '
        code info@fourth-strike.net
        = ' '
        span for an email with  the subject line 'IAM8BIT, INC Qx 20xx Royalty Statement' (sent quarterly)
      li Open the attachment and look for the latest quarter information
      li
        span Go
        = ' '
        a href=iam8bit_sales_path here
        = ' '
        span and "Add" records for both Wholesale and regular sales