config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/albums/bandcamp_details', to: 'albums#extract_bandcamp_details', as: 'extract_bandcamp_details'

  resources :artists, :payees, :payouts, :albums, :tracks

  resources :merch_orders, path: '/merch/orders'
  put '/merch/orders/:id/refund', to: 'merch_orders#refund', as: 'refund_merch_order'
  resources :merch_fulfillments, path: '/merch/orders/fulfillments'

  resources :iam8bit_sales, path: 'merch/iam8bit'
  resources :merch
  resources :rendered_services, path: 'services_rendered'

  get '/reports', to: 'reports#index'
  get '/reports/projects', to: 'reports#projects'
  get '/reports/generate', to: 'reports#combined_excel_report', as: 'reports_generate'
  get '/reports/profit_and_loss', to: 'reports#profit_and_loss'
  get '/reports/:id/download', to: 'reports#download', as: 'reports_download'
  get '/issues', to: 'reports#needs_attention'

  scope path: '/products/:product_type/:product_id/splits' do
    get '/edit', to: 'splits#edit', as: 'edit_splits'
    post '/', to: 'splits#update', as: 'splits'

    post '/append', to: 'splits#append', as: 'append_split'
  end

  get '/imports', to: 'imports#index', as: 'imports'
  post '/imports/distrokid', to: 'imports#import_distrokid_streams'
  post '/imports/bandcamp', to: 'imports#import_bandcamp_sales'

  match '/internal/jobs' => DelayedJobWeb, :anchor => false, :via => [:get, :post], as: 'delayed_jobs'

  get '/privacy', to: 'static_pages#privacy'
  root 'static_pages#home'
end

app/models/report.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: reports
#
#  id              :integer          not null, primary key
#  args            :json             not null
#  error_message   :text
#  filename        :string           not null
#  generated_at    :datetime         not null
#  state           :integer          default("pending"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  generated_by_id :integer          not null
#
# Indexes
#
#  index_reports_on_generated_by_id  (generated_by_id)
#
# Foreign Keys
#
#  generated_by_id  (generated_by_id => admins.id)
#

# Reports can take a while to generate, so this table keeps track of progress
# so that the app is still usable while the report is being generated.
class Report < ApplicationRecord
  self.inheritance_column = '_type'

  belongs_to :generated_by, class_name: 'Admin'

  enum :state,
       pending: 0,
       running: 1,
       completed: 2,
       failed: -1

  def generate!
    GenerateReportJob.perform_later(id)
  end

  before_save do |report|
    report.filename ||= default_filename
    report.generated_at ||= Time.zone.now
  end

  after_destroy do |report|
    File.delete(report.path)
  rescue Errno::ENOENT
    # already deleted
  end

  def time_range
    (self.begin...self.end)
  end

  def interval
    ActiveSupport::Duration.parse(args['interval'])
  end

  def path
    Rails.root.join("storage/reports/#{id}/#{filename}")
  end

  def builder
    ReportBuilder.new(time_range: time_range, interval: interval)
  end

  private

  def default_filename
    org_name = Rails.application.config.app_config[:organization_name]
    "#{org_name.underscore}_reports_#{self.begin.to_date.iso8601}_#{self.end.to_date.iso8601}.xlsx"
  end

  def begin
    Time.zone.parse(args['begin'])
  end

  def end
    Time.zone.parse(args['end'])
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :raise_unless_admin!

  def index
    @streaming_data = DistrokidSale.streams_per_month
    @sale_data = BandcampSale.sales_by_month.transform_values { |h| h.transform_values(&:amount) }
    @reports = Report.includes(:generated_by).order(generated_at: :desc).paginate(page: params[:page] || 1,
                                                                                  per_page: 50)
  end

  def projects
    @albums = Album.includes(:tracks, :merch_items, :splits).order(release_date: :desc)
    @albums = @albums.where('lower(artist_name) like ?', params[:artist].downcase) if params[:artist]
    @project_profit_data = @albums.map(&:project).reverse.map do |project|
      {
        name: project.name,
        organization_profit: project.organization_profit.round.to_f,
        distributable_income: project.distributable_income.round.to_f
        # bandcamp_downloads
        # streams: project.total_streams,
      }
    end
  end

  def profit_and_loss
    tr_start = params[:from].present? ? Time.zone.parse(params[:from]) : 1.year.ago
    tr_end = params[:to].present? ? Time.zone.parse(params[:to]) : (tr_start + 1.year)
    @time_range = tr_start...tr_end
    @stats = ProfitAndLossCalculator.new(@time_range)
  rescue StandardError => e
    flash[:danger] = e.message
    redirect_to reports_path
  end

  def combined_excel_report
    from = Time.zone.parse(params[:from])
    to = Time.zone.parse(params[:to])
    report = Report.create!(
      generated_at: Time.zone.now,
      generated_by: current_user.admin,
      args: { begin: from.iso8601, end: to.iso8601, interval: params[:interval] }
    )
    report.generate!
    flash[:success] = 'The report will be ready to download in a few minutes.'
    redirect_to reports_path
  end

  def download
    report = Report.find(params[:id])
    if report.completed?
      send_file(report.path, type: 'application/vnd.ms-excel', disposition: 'attachment')
    else
      flash[:danger] = 'This report is not completed'
      redirect_to reports_path
    end
  end

  def needs_attention
    @due_for_payout = Payee.due_for_payout
    @missing_payee_info = Payee.missing_payment_info
    @missing_splits = [Album, Track, Merch].map(&:without_splits).map(&:count).sum
  end
end

app/views/reports/_pnl_form.html.slim
= form_tag(reports_profit_and_loss_path, method: :get, class: "form", 'data-turbo' => "false") do
    .field
      label.label = "From (inclusive)"
      .control
        = date_field_tag :from, params[:from] || 1.year.ago.to_date, class: 'input'
    .field
      label.label = "To (exclusive)"
      .control
        = date_field_tag :to, params[:to] || Time.zone.now.to_date, class: 'input'
    
    .field
      .control
        = submit_tag "Generate P&L", class: "button is-primary"

app/views/reports/index.html.slim
section.section  
  .columns
    .column
      h3.is-size-4 Streaming Volume

      div vue-component="StreamingChart" props={data: @streaming_data }.to_json

      p.help NOTE: Due to reporting delays, recent data will be under-represented.

    .column
      h3.is-size-4 Sales

      div vue-component="SaleChart" props={data: @sale_data }.to_json

section.section
  h1.is-size-2 Interactive Reports

  ul
    li
      a href=reports_projects_path Projects
    li
      a href=iam8bit_sales_path iam8bit Sales
    li
      a href=issues_path Needs Attention
    li
      span Profit & Loss
      = render 'pnl_form'

section.section
  h1.is-size-2 Generate Report

  = form_tag(reports_generate_path, method: :get, class: "form", 'data-turbo' => "false") do
    .field
      label.label = "From (inclusive)"
      .control
        = date_field_tag :from, Time.zone.local(2020, 8, 1).to_date, class: 'input'
    .field
      label.label = "To (exclusive)"
      .control
        = date_field_tag :to, Time.zone.now.to_date, class: 'input'
    .field
      label.label = "Summary Interval"
      .control
        = select_tag(:interval, options_for_select([1.week, 1.month, 3.months, 1.year].to_h { |v| [v.inspect, v.iso8601] }, 1.month.iso8601), class: 'input')
    .field.is-grouped
      .control
        = submit_tag "Download Custom Report", class: "button is-primary"
      .control
        - tax_year_end = Time.zone.strptime(Rails.application.config.app_config[:tax_year_start], "%m-%d")
        - tax_year_start = tax_year_end - 1.year
        a.button href=reports_generate_path(from: tax_year_start.to_date.iso8601, to: tax_year_end.to_date.iso8601, interval: 'P1M') Download Previous Tax Year Report

section.section
  h1.is-size-2 Reports

  = render_pagination(@reports)

  table.table
    thead
      tr
        th Generated At
        th Report
        th Status
        th
    tbody
      - @reports.each do |report|
        tr
          td
            = localized_datetime(report.generated_at)
            - if report.generated_by.present?
              br
              = "by #{report.generated_by.discord_handle}"
          td
            code = report.filename
          td
            - if report.pending?
              span.tag.is-warning Pending
            - elsif report.running?
              span.tag.is-info Running
            - elsif report.completed?
              span.tag.is-success Completed
            - elsif report.failed?
              span.tag.is-danger Failed
          td
            - if report.completed?
              a href=reports_download_path(report.id) data-turbo="false" Download
        - if report.error_message.present?
          tr
            td colspan="4"
              pre.is-size-7 style="max-width: 50%; overflow: scroll" = report.error_message

  = render_pagination(@reports)

app/views/reports/needs_attention.html.slim
section.section
  h2.is-size-3 Needs Attention

  = render 'merch/unfulfilled'

  - if DistrokidSale.maximum(:created_at) < 1.month.ago
    article.message.is-warning
      .message-header
        span = "Streaming revenue is #{how_long_ago(DistrokidSale.maximum(:created_at), round: 1.week)} out of date"
      .message-body
        a href=imports_path Directions

  - if BandcampSale.maximum(:created_at) < 1.month.ago
    article.message.is-warning
      .message-header
        span = "Bandcamp sales are #{how_long_ago(BandcampSale.maximum(:created_at), round: 1.week)} out of date"
      .message-body
        a href=imports_path Directions

  - if Iam8bitSale.maximum(:created_at) < 3.months.ago
    article.message.is-warning
      .message-header
        span = "iam8bit sales report is #{how_long_ago(Iam8bitSale.maximum(:created_at), round: 1.month)} out of date"
      .message-body
        a href=imports_path Directions

  - unless @due_for_payout.empty?
    article.message.is-warning
      .message-header
        span = "#{@due_for_payout.count} payees are due to be paid out"
      .message-body
        = render 'payees/table', payees: @due_for_payout


  - unless @missing_payee_info.empty?
    article.message.is-warning
      .message-header
        span = "#{@missing_payee_info.count} payees are missing payment info"
      .message-body
        = render 'payees/table', payees: @missing_payee_info

  - if @missing_splits > 0
    article.message.is-warning
      .message-header
        span = "#{@missing_splits} products are missing royalty split assignments"
      .message-body
        .columns
          .column
            table.table
              thead
                tr
                  th Albums
                  th
              tbody
                - Album.without_splits.order(release_date: :desc).each do |album|
                  tr
                    td
                      a href=album_path(album) = album.name
                      br
                      span = "by #{album.artist_name}"
                    td
                      a href=edit_splits_path(product_type: 'Album', product_id: album.id) Edit
          .column
            table.table
              thead
                tr
                  th Tracks
                  th
              tbody
                - Track.without_splits.order_by_release_date_desc.each do |track|
                  tr
                    td
                      a href=track_path(track) = track.name
                      br
                      span = "from #{track.album.name} by #{track.album.artist_name}"
                    td
                      a href=edit_splits_path(product_type: 'Track', product_id: track.id) Edit
          .column
            table.table
              thead
                tr
                  th Merch
                  th
              tbody
                - Merch.without_splits.order(id: :desc).each do |merch|
                  tr
                    td
                      a href=merch_path(merch) = merch.name
                    td
                      a href=edit_splits_path(product_type: 'Merch', product_id: merch.id) Edit
  

app/views/reports/profit_and_loss.html.slim
section.section
  h2.is-size-3 Profit & Loss Report

  = render 'pnl_form'

  h3.is-size-4 Revenue
  table.table
    thead
      tr
        th Type
        th Gross
        th Net
    tbody
      tr
        td Digital Sales
        td = @stats.digital_gross_revenue.round.format
        td = @stats.digital_net_revenue.round.format
      tr
        td Streaming
        td = @stats.streaming_gross_revenue.round.format
        td = @stats.streaming_net_revenue.round.format
      tr
        td Merch
        td = @stats.merch_gross_revenue.round.format
        td = @stats.merch_net_revenue.round.format

  h3.is-size-4 Debts
  table.table
    thead
      tr
        th Type
        th Owed
        th Paid
        th Outstanding
    tbody
      tr
        td Charity
        td = @stats.charity_dues.round.format
        td = @stats.charities_paid.round.format
        td = @stats.charity_outstanding.round.format
      tr
        td Artist Royalties & Services Rendered
        td 
          = @stats.artist_royalties_and_services_owed.round.format
          br
          span.is-italic Royalties:
          = ' '
          = @stats.artist_royalties_earned.round.format
          br
          span.is-italic Services:
          = ' '
          = @stats.services_rendered_owed.round.format
        td = @stats.artist_royalties_and_services_paid.round.format
        td = @stats.artist_outstanding.round.format

  h4.is-size-4
    span Organization Profit:
    = ' '
    = @stats.organization_profit.round.format

app/views/reports/projects.html.slim
section.section
  div vue-component="ProjectChart" props={ data: @project_profit_data }.to_json

= render partial: 'albums/accounting', locals: { albums: @albums }